# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache: packages
r_github_packages: lbusett/sprawl

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

matrix:
  include:
    - os: linux
      dist: trusty
      env:
      global:
      - R_BUILD_ARGS=" "
      - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
      - R_CHECK_TIMINGS_="0"
    #  - BOOTSTRAP_LATEX="1"
      addons:
        apt:
          packages:
            - libcairo2-dev
            - libatk1.0-dev
            - libpango1.0-dev
            - libgtk2.0-dev
            - libglib2.0-dev
            - libcurl4-openssl-dev
            - libgdal-dev
            - libproj-dev
            - units
            - libudunits2-dev
      r_binary_packages:
        - cairoDevice
        - RGtk2

r_packages:
  - covr
  - sf
