language: R
sudo: required
dist: xenial
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'ppa:marutter/c2d4u'
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - python-gdal
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal

r:
  - release
  - devel

r_binary_packages:
  - sys
  - askpass
  - lazyeval
  - curl
  - mime
  - openssl
  - R6
  - DBI
  - digest
  - jsonlite
  - rex
  - httr
  - crayon
  - withr
  - yaml
  - RPostgreSQL
  - covr
  - sf
  - stars
  - data.table
  - raster
  - rgdal
  - XML
  - geojsonio
  - foreach
  - doParallel
  - RcppTOML
  - leaflet
  - leafpm
  - mapedit
  - shiny
  - shinyFiles
  - shinydashboard
  - shinyjs
  - shinyWidgets
  - spelling
  - geojsonlint
  - httptest
  - knitr
  - rmarkdown
  - units
  - testthat
  - e1071
  - Rcpp
  - classInt
  - magrittr
  - sp
  - urltools
  - httpcode
  - triebeard
  - tibble
  - hms
  - clipr
  - BH
  - pkgconfig
  - rlang
  - vctrs
  - cli
  - ellipsis
  - fansi
  - lifecycle
  - pillar
  - assertthat
  - glue
  - utf8
  - protolite
  - jqr
  - iterators
  - htmltools
  - xfun
  - farver
  - labeling
  - munsell
  - RColorBrewer
  - viridisLite
  - colorspace
  - ggplot2
  - gridExtra
  - gtable
  - isoband
  - scales
  - evaluate
  - pkgload
  - praise
  - desc
  - pkgbuild
  - rprojroot
  - rstudioapi
  - callr
  - prettyunits
  - backports
  - processx
  - ps
  - tidyselect
  - plogr
  - purrr
  - base64enc
  - crosstalk
  - htmlwidgets
  - markdown
  - png
  - viridis
  - leaflet.providers
  - mapdeck
  - colourvalues
  - googlePolylines
  - geojsonsf
  - jsonify
  - sfheaders
  - rapidjsonr
  - spatialwidget
  - httpuv
  - xtable
  - sourcetools
  - later
  - promises
  - fastmap
  - stringr
  - stringi
  - dplyr
  - leafem
  - leafpop
  - satellite
  - webshot
  - brew
  - svglite
  - uuid
  - plyr
  - gdtools
  - systemfonts
  - highr
  - V8
  - abind
  - lwgeom
  - rgeos
  - crul
  - maptools
  - readr
  - geojson
  - leaflet.extras
  - mapview
  - miniUI
  - fs
  - commonmark
  - xml2
  - hunspell
  - jsonvalidate
  - tinytex

before_script:
  - mkdir $HOME/.sen2r
  - echo "user user" > $HOME/.sen2r/apihub.txt
  
script: 
  - R CMD build .
  - travis_wait 120 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change

