language: R
sudo: required
dist: xenial
cache: packages
r:
  - release
  - devel

r_packages:
  - RPostgreSQL
  - covr

r_github_packages:
  - r-spatial/lwgeom

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - protobuf-compiler
  - valgrind
  - libjq-dev
  - python-numpy
  - python-gdal
  - aria2

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev libv8-dev libprotobuf-dev libudunits2-dev netcdf-bin libv8-dev libjq-dev
  - sudo apt-get install -y gdal-bin python-gdal

before_script:
  - mkdir $HOME/.sen2r
  - Rscript -e 'sen2r::load_binpaths(c("python", "aria2", "gdal"))'
  - Rscript -e 'sen2r::write_scihub_login("user", "user")'

script: 
  - R CMD build .
  - travis_wait 120 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change

