language: R
sudo: required
dist: bionic
cache: packages

r_packages:
  - RPostgreSQL
  - covr

r_github_packages:
  - r-spatial/lwgeom

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - protobuf-compiler
  - valgrind
  - libjq-dev
  - python-numpy
  - python-gdal
  - aria2

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev libv8-dev libprotobuf-dev libudunits2-dev netcdf-bin libv8-dev libjq-dev

script: 
  - R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/s2_gui.R", "R/add_rgb_image.R", "R/geograbber_process.R", "R/editModPoly.R", "R/install_aria2.R", "R/install_sen2cor.R", "R/create_s2_dop.R"))'

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change

