language: R
sudo: required
dist: xenial
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal
      - libproj-dev
      - libgdal-dev
      
before_install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_github("cran/XML")' # required for R 3.6.3

r:
  - release
  - devel
  - oldrel

r_packages:
  - RPostgreSQL
  - covr

before_script:
  - mkdir $HOME/.sen2r

script: 
  - R CMD build .
  - travis_wait 50 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"
    - secure: "S4ePkCel1HyiuHBAGKn6iUAxgFl5jEvaVntYozoFjAiiZ6MNL+mDpgYOnHc/5yR77ydfYvB0rqPhl04SD3ymVWonwFYh+gJcXa2RgTaxC6BrVZGVjXJPwZ9K4497cpziPRDNp58Jbr6wgC/iP/itj0y8C0Fdoac28XJRdGDhndBvgismp7fA5HJxFFELqTKx2fzLuVnhMq5X+IIYVLxDbK7YVSp7aIsSdz+Yc7hIrjQsDuGCfgHHbQsGcDve85i3bOjnVDDOgoN5b8EPfjvb8qK6WnL9dmWNhCjArRDw5TKovkv1/qJ+VIuadOYp14bkDENl0F4c+YeNRups1tR7xXj384N/kVN/Ehi8Z5KOsfuwMT9Z5cc+6+F82ETNMpUQ/xXPfwas3uaj4dIfHsacs35Ben0m8sPOa6Loj0NUpQ/5Wh2pwHiRwf/ilsW2Bnw2I8mAFzUfnT31j5wF8pbG3avTx+/roalgUCptt8yaTFiDu5Kk54G67qW6LjGj5YeodDvn1LmVkJeVZDZjS/eFNMe3qtu2DGXLhrzcD/zUcMFjcTgtNAJmOUYOu6gfgt6PonXREFEg4KtyrGWA/AVnlUpNOUvu33JCmNKCZbAzVj8GfAybUIYEbmnF63NN9+bCzzwGRRjkiAz3TCnBtSMFG20CChq2EJPwHuNdqV/8SiU="

notifications:
  email:
    on_success: change
    on_failure: change
